projects:
  amplifychatangular:
    schemaPath: amplify/backend/api/amplifychatangular/build/schema.graphql
    includes:
      - src/graphql/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        maxDepth: 2
extensions:
  amplify:
    version: 3
